<?php /** @var T4webTimeline\Controller\User\ListViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="page-header">
    <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-align-left page-header-icon"></i>&nbsp;&nbsp;Timeline</h1>

    <div class="col-xs-12 col-sm-8">
        <div class="row">
            <!-- "Create project" button, width=auto on desktops -->
            <div class="pull-right col-xs-12 col-sm-auto">
                <a style="width: 100%;" class="btn btn-primary btn-labeled" href="<?=$this->url('timeline-add');?>">
                    <span class="btn-label icon fa fa-plus"></span>Add entry</a>
            </div>
        </div>
    </div>
</div> <!-- / .page-header -->

<form class="panel form-horizontal" action="#">
    <div class="panel-heading">
        <span class="panel-title"><i class="fa fa-filter"></i> Filter</span>
    </div>
    <div class="panel-body">
        <div class="row form-group">
            <label class="col-sm-1 control-label">Type:</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="name">
            </div>

            <label class="col-sm-1 control-label">Date:</label>
            <div class="col-sm-5">
                <input type="email" class="form-control" name="email">
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <button class="btn btn-primary">Submit</button>
        <button class="btn btn-default">Reset</button>
    </div>
</form>

<?= $this->timeline(null); ?>