<?php /** @var T4webTimeline\View\Helper\TimelineViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="timeline">
    <!-- Timeline header -->
    <div class="tl-header now">Now</div>

    <?php /** @var T4webTimeline\Entry\Entry $entry */ ?>
    <?php foreach($viewModel->getCollection() as $entry): ?>
        <?=$this->render($viewModel->getRenderer($entry))?>
    <?php endforeach; ?>
</div>