<?php /** @var T4webTimeline\View\Helper\TimelineViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="timeline">
    <!-- Timeline header -->
    <div class="tl-header now">Now</div>

    <?php /** @var T4webTimeline\Entry\Entry $entry */ ?>
    <?php foreach($viewModel->getCollection() as $entry): ?>
        <div class="tl-entry">
            <div class="tl-time">
                <?=$entry->getCreationDate()?>
            </div>
            <div class="tl-icon bg-success"><img alt="" src="/assets/demo/avatars/2.jpg"></div>
            <div class="panel tl-body">
                <a href="#">Denise Steiner</a> shared an image on <a href="#">The Gallery</a>
            </div>
        </div>
    <?php endforeach; ?>
<!--
    <div class="tl-entry">
        <div class="tl-time">
            1h ago
        </div>
        <div class="tl-icon bg-warning"><i class="fa fa-envelope"></i></div>
        <div class="panel tl-body">
            <h4 class="text-warning">Lorem ipsum dolor sit amet</h4>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
    </div>

    <div class="tl-entry left">
        <div class="tl-time">
            2h ago
        </div>
        <div class="tl-icon bg-success"><i class="fa fa-picture-o"></i></div>
        <div class="panel tl-body">
            <a href="#">Denise Steiner</a> shared an image on <a href="#">The Gallery</a>
            <div style="padding: 10px;margin-top:15px;margin-bottom: 15px;background: #f1f1f1" class="tl-wide text-center">
                <img style="max-height: 150px;max-width: 100%;" alt="" src="/assets/demo/signin-bg-5.jpg">
            </div>
            <i class="text-muted text-sm">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</i>
        </div>
    </div>

    <div class="tl-entry">
        <div class="tl-time">
            3h ago
        </div>
        <div class="tl-icon bg-success"><img alt="" src="/assets/demo/avatars/2.jpg"></div>
        <div class="panel tl-body">
            <a href="#">Robert Jang</a> commented on <a href="#">The Article</a>
            <div style="margin: 10px 0 0 0;" class="well well-sm">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
        </div>
    </div>

    <div class="tl-entry left">
        <div class="tl-time">
            4h ago
        </div>
        <div class="tl-icon bg-dark-gray"><i class="fa fa-check"></i></div>
        <div class="panel tl-body">
            <img style=" width: 20px;height: 20px;margin-top: -2px;" class="rounded" alt="" src="/assets/demo/avatars/5.jpg">&nbsp;&nbsp;<a href="#">Denise Steiner</a> followed <a href="#">Johg Doe</a>
        </div>
    </div>


    <div class="tl-header">Yesterday</div>

    <div class="tl-entry">
        <div class="tl-time">
            9:02 pm
        </div>
        <div class="tl-icon bg-info"><i class="fa fa-comment"></i></div>
        <div class="panel tl-body">
            <a href="#">Denise Steiner</a> liked a comment on <a href="#">Some Article</a>
            <div class="text-sm" style="margin-top: 10px;">
                <img style=" width: 20px;height: 20px;margin-top: -2px;" class="rounded" alt="" src="/assets/demo/avatars/3.jpg">&nbsp;&nbsp;<a href="#">Michelle Bortz</a> commented 2 days ago
                <div style="margin: 6px 0 0 0;" class="well well-sm">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
            </div>
        </div>
    </div>

    <div class="tl-entry left">
        <div class="tl-time">
            5:47 pm
        </div>
        <div class="panel tl-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div>
    </div>

    <div class="tl-entry">
        <div class="tl-time">
            2:35 pm
        </div>
        <div class="tl-icon bg-danger"><i class="fa fa-heart"></i></div>
        <div class="panel tl-body">
            <a href="#">Denise Steiner</a> liked <a href="#">Shop Item</a>
        </div>
    </div>

    <div class="tl-entry left">
        <div class="tl-time">
            11:21 am
        </div>
        <div class="panel tl-body">
            <h4 class="text-danger">Lorem ipsum dolor sit amet</h4>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
    </div>
    -->

</div>